version: "3.8"

services:
  neo:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: neo
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn main:app --host 0.0.0.0 --port 8000
